### PR TITLE
add Podcasts link to navbar

### PR DESCRIPTION
**Pull request by antograssiot**

### CODE REVIEW

**Comment by jameswatts** [comment]
I'm not sure if the "Podcasts" option makes much sense after the "Logo", maybe before the CakeFest link?

Also, it's a single "Podcast", with many episodes, not many podcasts, i.e: Podcast hasMany Episode :cake:

**Comment by antograssiot** [comment]
@jameswatts OK I'll modify that. Would you like to include also links to "My CakePHP" and "Community Center" as in my.cakephp.org ?

**Comment by jameswatts** [comment]
@antograssiot yeah, I've been wanting to "fix" the menus for a while, @ravage84 also put in a proposal to restructure them.

See what you can do, we definitely need to reduce the noise, but also make sure that people can discover and access things. Options like Facebook, Google+, Twitter and YouTube for example are also found from the http://community.cakephp.org portal, so we could probably remove those?

Additionally, the "certification" option needs to point to http://certification.cakephp.org now.

**Comment by ravage84** [comment]
@jameswatts I was thinking restarting my previous PR https://github.com/cakephp/csfnavbar/pull/2

**Comment by antograssiot** [comment]
@ravage84  Sorry I didn't saw/check that you already have a PR for the menus. This modification could totally be part of it.

**Comment by ravage84** [comment]
@antograssiot no problem. My PR is up already quite some time now.
We had some viewport related problems. May be you can help me to get that fixed.
I'll include your addition from this PR, too.

**Pull request closed without merging**
